title: "Maël Chiotti"

name: "Maël Chiotti"
email: "mael.chiotti@rvandco.fr"

description: >
  Welcome to my personal website!

theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/maelchiotti" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/maelchiotti/" }

header_pages:
  - about.md
