title: Maël Chiotti
description: >
  Welcome to my personal website!
author:
  name: Maël Chiotti
  mail:

theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/maelchiotti" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/maelchiotti/" }

header_pages:
  - about.md
  - portfolio.md
