title: "Maël Chiotti"

description: >
  Welcome to my personal website!

name: "Maël Chiotti"
email:

theme: minima

github_username: maelchiotti
linkedin_username: maelchiotti
facebook_username: mael.chiotti
youtube_username: "@studiorvandco"

header_pages:
  - about.md
